# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Major.create( abbreviation: "BACC", name: "Accounting (BS)" )
Major.create( abbreviation: "SANT", name: "Anthropology (BS)" )
Major.create( abbreviation: "SACS", name: "Applied Cognitive Science and Human Factors (MS PhD)" )
Major.create( abbreviation: "BNRE", name: "Applied Natural Resource Economics (MS)" )
Major.create( abbreviation: "IAS", name: "Atmospheric Sciences (PhD)" )
Major.create( abbreviation: "SFAT", name: "Audio Production & Technology (BS)" )
Major.create( abbreviation: "IBMB", name: "Biochemistry & Molecular Biology (PhD)" )
Major.create( abbreviation: "SMBB", name: "Biochemistry and Molecular Biology-Bio (BS)" )
Major.create( abbreviation: "SMBC", name: "Biochemistry and Molecular Biology-Chem (BS)" )
Major.create( abbreviation: "SBI", name: "Bioinformatics (BS)" )
Major.create( abbreviation: "SBL", name: "Biological Sciences (BS MS PhD)" )
Major.create( abbreviation: "EBE", name: "Biomedical Engineering (BS MS PhD)" )
Major.create( abbreviation: "BBA", name: "Business Administration (BS)" )
Major.create( abbreviation: "BMBA", name: "Business Administration (MBA)" )
Major.create( abbreviation: "ECM", name: "Chemical Engineering (BS MS PhD)" )
Major.create( abbreviation: "SCHI", name: "Cheminformatics (BS)" )
Major.create( abbreviation: "SCH", name: "Chemistry (BS MS PhD)" )
Major.create( abbreviation: "ECE", name: "Civil Engineering (BS MS PhD)" )
Major.create( abbreviation: "SCL", name: "Clinical Laboratory Science (BS)" )
Major.create( abbreviation: "SCCM", name: "Communication, Culture and Media (BA)" )
Major.create( abbreviation: "EPD5", name: "Computational Science Engineering (PhD)" )
Major.create( abbreviation: "ECP", name: "Computer Engineering (BS MS PhD)" )
Major.create( abbreviation: "TCSA", name: "Computer Network & System Administration (BS)" )
Major.create( abbreviation: "SCS", name: "Computer Science (BS MS PhD)" )
Major.create( abbreviation: "SCSY", name: "Computer Systems Science (BS)" )
Major.create( abbreviation: "TCMG", name: "Construction Management (BS)" )
Major.create( abbreviation: "FES", name: "Ecology, Applied  and Environmental Sciences (BS)" )
Major.create( abbreviation: "FAE", name: "Ecology, Applied (MS)" )
Major.create( abbreviation: "BEC", name: "Economics (BS)" )
Major.create( abbreviation: "SASE", name: "Education, Applied Science (MS)" )
Major.create( abbreviation: "BEC2", name: "Education, Secondary " )
Major.create( abbreviation: "TEET", name: "Electrical Eng Tech (BS)" )
Major.create( abbreviation: "EEE", name: "Electrical Engineering (BS MS PhD)" )
Major.create( abbreviation: "EPD", name: "Engineering (PHD)" )
Major.create( abbreviation: "EBS", name: "Engineering / Service System Engineering (BS)" )
Major.create( abbreviation: "BEM", name: "Engineering Management (BS)" )
Major.create( abbreviation: "EEM", name: "Engineering Mechanics (MS)" )
Major.create( abbreviation: "SPE", name: "Engineering Physics (PhD)" )
Major.create( abbreviation: "TAET", name: "Engineering Technology (AAS)" )
Major.create( abbreviation: "EGN", name: "Engineering, General (BS)" )
Major.create( abbreviation: "EPD2", name: "Engineering-Environmental Engineering (PhD)" )
Major.create( abbreviation: "SEN", name: "English (BA)" )
Major.create( abbreviation: "SEEP", name: "Environmental & Energy Policy (PhD)" )
Major.create( abbreviation: "EEN", name: "Environmental Engineering (BS MEG PhD)" )
Major.create( abbreviation: "EENS", name: "Environmental Engineering Science (MS)" )
Major.create( abbreviation: "SSEP", name: "Environmental Policy (MS)" )
Major.create( abbreviation: "SESC", name: "Exercise Science (BS)" )
Major.create( abbreviation: "BFIN", name: "Finance (BS)" )
Major.create( abbreviation: "FFEM", name: "Forest Ecology & Management (MS)" )
Major.create( abbreviation: "FMGB", name: "Forest Molecular Genetics and Biotechnology (MS PhD)" )
Major.create( abbreviation: "FFS", name: "Forest Science (PhD)" )
Major.create( abbreviation: "FFR", name: "Forestry (BS, MS)" )
Major.create( abbreviation: "TGN", name: "General Technology" )
Major.create( abbreviation: "EGE", name: "Geological Engineering (BS MS PhD)" )
Major.create( abbreviation: "EGL", name: "Geology (BS MS PhD)" )
Major.create( abbreviation: "EGP", name: "Geophysics (MS PhD)" )
Major.create( abbreviation: "EAG", name: "Geophysics, Applied (BS)" )
Major.create( abbreviation: "SAH", name: "Humanities (ASC)" )
Major.create( abbreviation: "SSM", name: "Industrial Archaeology (MS)" )
Major.create( abbreviation: "SIHA", name: "Industrial Heritage Archaeology (PhD)" )
Major.create( abbreviation: "BBA4", name: "Industrial Marketing and Management" )
Major.create( abbreviation: "TGT", name: "Integrated Geospatial Technology (MS)" )
Major.create( abbreviation: "SHU", name: "Liberal Arts (BA)" )
Major.create( abbreviation: "BMGT", name: "Management (BS)" )
Major.create( abbreviation: "BMIS", name: "Management Information Systems (BS)" )
Major.create( abbreviation: "BMKT", name: "Marketing (BS)" )
Major.create( abbreviation: "EGR", name: "Master of Engineering (MEG)" )
Major.create( abbreviation: "EGR3", name: "Master of Engineering - Civil Engineering" )
Major.create( abbreviation: "EGR4", name: "Master of Engineering - Environmental Engineering" )
Major.create( abbreviation: "FMF", name: "Master of Forestry" )
Major.create( abbreviation: "EMSE", name: "Materials Science & Engineering (BS MS PhD)" )
Major.create( abbreviation: "SMAG", name: "Mathematical Sciences (MS PhD)" )
Major.create( abbreviation: "SMA", name: "Mathematics (BS)" )
Major.create( abbreviation: "EME", name: "Mechanical Engineering (BS MS)" )
Major.create( abbreviation: "TMET", name: "Mechanical Engineering Technology (BS)" )
Major.create( abbreviation: "MEEM", name: "Mechanical Engineering-Engineering Mechanics (PhD)" )
Major.create( abbreviation: "TMIN", name: "Medical Informatics (MS)" )
Major.create( abbreviation: "BME", name: "Mineral Economics (MS)" )
Major.create( abbreviation: "EMG", name: "Mining Engineering (MS PhD)" )
Major.create( abbreviation: "BOSM", name: "Operations & Systems Management  (BS)" )
Major.create( abbreviation: "SCHP", name: "Pharmaceutical Chemistry (BS)" )
Major.create( abbreviation: "SPH", name: "Physics (BS MS PhD)" )
Major.create( abbreviation: "SAP", name: "Physics, Applied (BS)" )
Major.create( abbreviation: "SPSY", name: "Psychology (BS)" )
Major.create( abbreviation: "SRC", name: "Rhetoric & Technical Communication (MS PhD)" )
Major.create( abbreviation: "STA", name: "Scientific & Tech Comm (BA)" )
Major.create( abbreviation: "STC", name: "Scientific & Tech Comm (BS)" )
Major.create( abbreviation: "SSS", name: "Social Sciences (BS)" )
Major.create( abbreviation: "SSEN", name: "Software Engineering (BS)" )
Major.create( abbreviation: "SFSD", name: "Sound Design (BA)" )
Major.create( abbreviation: "SSFM", name: "Sports and Fitness Management (BS)" )
Major.create( abbreviation: "TSE", name: "Surveying Engineering (BS)" )
Major.create( abbreviation: "SEMP", name: "Theatre & Electronic Media Performance (BA)" )
Major.create( abbreviation: "SFTT", name: "Theatre & Entertain Tech (BA)" )
Major.create( abbreviation: "SFET", name: "Theatre & EntertainTech (BS)" )
Major.create( abbreviation: "FWEM", name: "Wildlife Ecology & Management (BS)" )
Major.create( abbreviation: "FWF", name: "Wood Science" )